version: "3"

volumes:
  data:

services:
  #app:
    #build: .
    #ports:
      #- "3000:3000"
    #command: sh -c "yarn start"
    #volumes:
      #- .:/usr/app

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - data:/var/lib/postgres/data
